[package]
name = "starkciv"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.13.1"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.56.0" }

[[target.starknet-contract]]
sierra = true
casm = true
